name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: next build & now deploy
      run: |
        yarn install
        yarn build
        now --prod --scope youngtech --token $NOW_TOKEN
      env:
        CI: true
        NOW_TOKEN: ${{secrets.NOW_TOKEN}}
