name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: install now
      run:  npm i -g now@latest
    - name: next build & now deploy
      run: |
        yarn build
        now --prod
      env:
        CI: true
        token: ${{secrets.NOW_TOKEN}}
